name: Cross-Platform CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test (default: main)'
        required: true
        default: 'main'
      run_on_mac:
        description: 'Run tests on macOS?'
        required: false
        default: 'true'
      run_on_linux:
        description: 'Run tests on Linux?'
        required: false
        default: 'true'

jobs:
  test-linux:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_on_linux == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: pannagram
          create-args: --platform=linux-64

      - name: Activate environment and run tests
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate pannagram
          .github/ci_scripts/run_tests.sh

  test-macos:
    runs-on: macos-latest
    if: ${{ inputs.run_on_mac == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: pannagram
          create-args: --platform=osx-64

      - name: Activate environment and run tests
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate pannagram
          .github/ci_scripts/run_tests.sh